import { createClient } from 'npm:@supabase/supabase-js@2'

const cors = { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type' }
const ALLOWED_URGENCY = new Set(['standard', 'urgent', 'emergency'])
const HIGH_RISK = /\b(gas|boiler|carbon monoxide|co alarm|smell of gas|gas leak|sparking|spark|electrical|electric shock|live wire|burning smell|fire|smoke|flood|burst pipe|ceiling collapse|structural|collapse|sewage|raw sewage)\b/i

function fallback(description: string, category?: string) {
  const risk = HIGH_RISK.test(description)
  const urgency = risk ? (/(gas|carbon monoxide|fire|smoke|electric shock|live wire)/i.test(description) ? 'emergency' : 'urgent') : 'standard'
  const safety = urgency === 'emergency' ? 'This may involve an immediate safety hazard. Move to a safe location and contact the appropriate UK emergency or utility service where necessary. Do not attempt dangerous repairs yourself.' : urgency === 'urgent' ? 'A qualified professional should assess this promptly. Avoid opening, dismantling or repairing hazardous equipment yourself.' : 'A qualified professional can confirm the cause and required repair.'
  return { category: category || 'Other', urgency, safety_level: urgency === 'emergency' ? 'immediate_danger' : urgency, summary: `MEND could not complete an external AI assessment. The issue has been recorded as ${category || 'Other'} based on the information provided.`, likely_causes: [], recommended_action: urgency === 'standard' ? 'Request a professional assessment.' : 'Seek prompt professional assistance.', evidence_to_collect: ['A clear photo of the affected area', 'A short description of when the issue started'], red_flags: risk ? ['Potential safety-related wording detected; professional assessment is recommended.'] : [], confidence: 0.25, model: 'fallback-safety-router' }
}
async function aiAssess(description: string, category: string | undefined, categories: string[]) { const key = Deno.env.get('AI_API_KEY'); if (!key) return fallback(description, category); const model = Deno.env.get('MEND_AI_MODEL') || 'gpt-5-mini'; const system = `You are MEND Triage, an advisory home-repair intake assistant for the UK. Never claim to diagnose, certify, inspect, or replace a qualified professional. Never provide dangerous DIY instructions. For gas, electrical, fire, structural, flooding, hazardous or other immediate-risk situations, prioritize safety and professional/emergency escalation. Return ONLY valid JSON with keys: category, urgency, safety_level, summary, likely_causes, recommended_action, evidence_to_collect, red_flags, confidence. urgency must be standard|urgent|emergency. safety_level must be standard|urgent|emergency|immediate_danger. confidence must be 0..1. Categories available: ${categories.join(', ')}`; const body = { model, messages: [{ role: 'system', content: system }, { role: 'user', content: `Problem: ${description}\nSelected category: ${category || 'not selected'}` }], response_format: { type: 'json_object' }, temperature: 0.1 }; const response = await fetch('https://api.openai.com/v1/chat/completions', { method: 'POST', headers: { Authorization: `Bearer ${key}`, 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); if (!response.ok) throw new Error(`AI provider returned ${response.status}`); const json = await response.json(); const content = json?.choices?.[0]?.message?.content; if (!content) throw new Error('AI provider returned no assessment'); const parsed = JSON.parse(content); if (!ALLOWED_URGENCY.has(parsed.urgency)) parsed.urgency = 'standard'; if (!['standard','urgent','emergency','immediate_danger'].includes(parsed.safety_level)) parsed.safety_level = parsed.urgency; parsed.confidence = Math.max(0, Math.min(1, Number(parsed.confidence) || 0)); parsed.model = model; return parsed }
Deno.serve(async (req) => { if (req.method === 'OPTIONS') return new Response('ok', { headers: cors }); try { const auth = req.headers.get('Authorization'); if (!auth) return Response.json({ error: 'Authentication required' }, { status: 401, headers: cors }); const supabase = createClient(Deno.env.get('SUPABASE_URL') ?? '', Deno.env.get('SUPABASE_ANON_KEY') ?? '', { global: { headers: { Authorization: auth } } }); const token = auth.replace(/^Bearer\s+/i, ''); const { data: { user }, error: userError } = await supabase.auth.getUser(token); if (userError || !user) return Response.json({ error: 'Authentication required' }, { status: 401, headers: cors }); const input = await req.json(); const description = String(input?.description || '').trim().slice(0, 4000); const selectedCategory = input?.category ? String(input.category).slice(0, 100) : undefined; if (description.length < 5) return Response.json({ error: 'Describe the problem in at least 5 characters.' }, { status: 400, headers: cors }); const { data: categories } = await supabase.from('service_categories').select('name').order('sort_order'); const result = await aiAssess(description, selectedCategory, (categories || []).map((x: any) => x.name)); if (HIGH_RISK.test(description) && result.urgency === 'standard') { result.urgency = 'urgent'; result.safety_level = 'urgent'; result.red_flags = [...(result.red_flags || []), 'Safety-related terms were detected in the description.']; } const { data: session, error } = await supabase.from('ai_triage_sessions').insert({ user_id: user.id, description, selected_category: selectedCategory, result, model: result.model, confidence: result.confidence, safety_level: result.safety_level }).select('id').single(); if (error) throw error; return Response.json({ ...result, triage_session_id: session.id }, { headers: { ...cors, 'Content-Type': 'application/json' } }); } catch (error) { const message = error instanceof Error ? error.message : 'Triage failed'; return Response.json({ error: message }, { status: 500, headers: { ...cors, 'Content-Type': 'application/json' } }); } })