import { useCallback, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router, useFocusEffect, useLocalSearchParams } from 'expo-router';
import { Button, Card, Chip, Input, SectionTitle, Status } from '@/components/UI';
import { createPropertyAsset, createPropertyRoom, getPropertyPassport, updateProperty, type Property, type PropertyAsset, type PropertyRoom } from '@/lib/api';
import { theme } from '@/constants/theme';

export default function PropertyDetail(){
 const {id}=useLocalSearchParams<{id:string}>(); const [data,setData]=useState<any>(null); const [loading,setLoading]=useState(true); const [editing,setEditing]=useState(false); const [room,setRoom]=useState(false); const [asset,setAsset]=useState(false); const [saving,setSaving]=useState(false);
 const [address,setAddress]=useState(''); const [city,setCity]=useState(''); const [postcode,setPostcode]=useState(''); const [type,setType]=useState('House'); const [ownership,setOwnership]=useState('owner_occupier'); const [roomName,setRoomName]=useState(''); const [assetName,setAssetName]=useState(''); const [assetType,setAssetType]=useState('Appliance');
 const load=useCallback(async()=>{if(!id)return;setLoading(true);try{const d=await getPropertyPassport(id);setData(d);setAddress(d.property.address_line_1);setCity(d.property.city);setPostcode(d.property.postcode);setType(d.property.property_type);setOwnership(d.property.ownership_type);}catch(e){Alert.alert('Could not load Home Passport',e instanceof Error?e.message:'Please try again.');}finally{setLoading(false);}},[id]); useFocusEffect(useCallback(()=>{load();},[load]));
 if(loading||!data)return <View style={s.center}><ActivityIndicator color={theme.colors.primary}/></View>;
 const p=data.property as Property;
 const save=async()=>{setSaving(true);try{await updateProperty(p.id,{address_line_1:address,city,postcode,property_type:type,ownership_type:ownership});setEditing(false);await load();}catch(e){Alert.alert('Could not save',e instanceof Error?e.message:'Please try again.')}finally{setSaving(false)}};
 const addRoom=async()=>{if(!roomName.trim())return;try{await createPropertyRoom(p.id,{name:roomName.trim(),room_type:roomName.trim()});setRoomName('');setRoom(false);await load();}catch(e){Alert.alert('Could not add room',e instanceof Error?e.message:'Please try again.')}};
 const addAsset=async()=>{if(!assetName.trim())return;try{await createPropertyAsset(p.id,{name:assetName.trim(),asset_type:assetType});setAssetName('');setAsset(false);await load();}catch(e){Alert.alert('Could not add asset',e instanceof Error?e.message:'Please try again.')}};
 return <ScrollView contentContainerStyle={s.page} showsVerticalScrollIndicator={false}>
   <Pressable onPress={()=>router.back()} style={s.back}><Ionicons name="arrow-back" size={21} color={theme.colors.primary}/><Text style={s.backText}>Homes</Text></Pressable>
   <Text style={s.kicker}>HOME PASSPORT</Text><Text style={s.title}>{p.address_line_1}</Text><Text style={s.sub}>{p.city} · {p.postcode}</Text>
   <Card><View style={s.row}><View><Text style={s.cardKicker}>PROPERTY</Text><Text style={s.cardTitle}>{p.property_type}</Text><Text style={s.meta}>{p.ownership_type.replaceAll('_',' ')}</Text></View><Status text="Active" type="success"/></View>{editing?<View style={{gap:12,marginTop:15}}><Input label="Address" value={address} onChangeText={setAddress}/><Input label="City" value={city} onChangeText={setCity}/><Input label="Postcode" value={postcode} onChangeText={setPostcode}/><Text style={s.label}>Property type</Text><View style={s.chips}>{['House','Flat','Bungalow','Other'].map(x=><Chip key={x} active={type===x} onPress={()=>setType(x)}>{x}</Chip>)}</View><Text style={s.label}>Occupancy / ownership</Text><View style={s.chips}>{[['owner_occupier','Owner'],['rented','Rented'],['landlord','Landlord'],['managed','Managed']].map(([v,l])=><Chip key={v} active={ownership===v} onPress={()=>setOwnership(v)}>{l}</Chip>)}</View><Button title="Save property" loading={saving} onPress={save}/><Button title="Cancel" variant="ghost" onPress={()=>setEditing(false)}/></View>:<Button title="Edit property" variant="secondary" onPress={()=>setEditing(true)}/>}</Card>
   <SectionTitle title="Rooms" action="Add" onPress={()=>setRoom(true)}/>{room&&<Card><Input label="Room name" value={roomName} onChangeText={setRoomName} placeholder="Kitchen"/><Button title="Add room" onPress={addRoom}/></Card>}{data.rooms.length?data.rooms.map((r:PropertyRoom)=><Card key={r.id}><View style={s.row}><View style={s.icon}><Ionicons name="grid-outline" size={21} color={theme.colors.primary}/></View><View style={{flex:1}}><Text style={s.itemTitle}>{r.name}</Text><Text style={s.meta}>{r.room_type||'Room'}</Text></View></View></Card>):<Text style={s.muted}>No rooms added yet.</Text>}
   <SectionTitle title="Assets & appliances" action="Add" onPress={()=>setAsset(true)}/>{asset&&<Card><Input label="Asset name" value={assetName} onChangeText={setAssetName} placeholder="Boiler"/><Text style={s.label}>Type</Text><View style={s.chips}>{['Appliance','Boiler','Electrical','Heating','Window','Other'].map(x=><Chip key={x} active={assetType===x} onPress={()=>setAssetType(x)}>{x}</Chip>)}</View><Button title="Add asset" onPress={addAsset}/></Card>}{data.assets.length?data.assets.map((a:PropertyAsset)=><Card key={a.id}><View style={s.row}><View style={s.icon}><Ionicons name="construct-outline" size={21} color={theme.colors.primary}/></View><View style={{flex:1}}><Text style={s.itemTitle}>{a.name}</Text><Text style={s.meta}>{a.asset_type}{a.brand?` · ${a.brand}`:''}{a.model?` · ${a.model}`:''}</Text></View>{a.warranty_end&&<Status text={`Warranty ${a.warranty_end}`} type="success"/>}</View></Card>):<Text style={s.muted}>No assets recorded yet.</Text>}
   <SectionTitle title="Repair history" action={data.repairs.length?'View repairs':undefined} onPress={()=>router.push('/(tabs)/repairs')}/>{data.repairs.length?data.repairs.slice(0,5).map((r:any)=><Card key={r.id}><Text style={s.itemTitle}>{r.title}</Text><Text style={s.meta}>{r.reference_code} · {r.status.replaceAll('_',' ')}</Text></Card>):<Card><Text style={s.itemTitle}>No repairs yet</Text><Text style={s.meta}>Repairs created for this home will appear here.</Text></Card>}
   <SectionTitle title="Maintenance"/>{data.maintenance.length?data.maintenance.slice(0,5).map((m:any)=><Card key={m.id}><Text style={s.itemTitle}>{m.title}</Text><Text style={s.meta}>{m.due_date||'No due date'} · {m.status}</Text></Card>):<Card><Text style={s.itemTitle}>No maintenance tasks</Text><Text style={s.meta}>Maintenance schedules will be attached to this property.</Text></Card>}
   <Button title="Property compliance" variant="secondary" onPress={()=>router.push(`/property/compliance?id=${p.id}`)}/><SectionTitle title="Documents"/>{data.documents.length?data.documents.slice(0,5).map((d:any)=><Card key={d.id}><View style={s.row}><Ionicons name="document-text-outline" size={20} color={theme.colors.primary}/><View style={{flex:1,marginLeft:10}}><Text style={s.itemTitle}>{d.title||d.document_type}</Text><Text style={s.meta}>{d.document_type}</Text></View></View></Card>):<Card><Text style={s.itemTitle}>No property documents</Text><Text style={s.meta}>Certificates, invoices and property records can be stored here.</Text></Card>}
 </ScrollView>
}
const s=StyleSheet.create({page:{padding:20,paddingTop:55,gap:14,backgroundColor:theme.colors.bg,flexGrow:1},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:theme.colors.bg},back:{flexDirection:'row',alignItems:'center',gap:7,marginBottom:3},backText:{fontWeight:'800',color:theme.colors.primary},kicker:{fontSize:11,fontWeight:'900',letterSpacing:1.5,color:theme.colors.muted},title:{fontSize:31,fontWeight:'900',marginTop:3},sub:{fontSize:14,color:theme.colors.muted,lineHeight:20},cardKicker:{fontSize:10,fontWeight:'900',letterSpacing:1.2,color:theme.colors.muted},cardTitle:{fontSize:20,fontWeight:'900',marginTop:4},meta:{fontSize:12,color:theme.colors.muted,marginTop:3,textTransform:'capitalize'},row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10},icon:{width:46,height:46,borderRadius:14,backgroundColor:'#EAF0F1',alignItems:'center',justifyContent:'center'},itemTitle:{fontSize:16,fontWeight:'900'},muted:{fontSize:13,color:theme.colors.muted,paddingHorizontal:4},label:{fontSize:13,fontWeight:'800',color:theme.colors.text},chips:{flexDirection:'row',flexWrap:'wrap',gap:8}});
