import { useCallback, useState } from 'react';
import { Alert, ScrollView, StyleSheet, Text, View, ActivityIndicator } from 'react-native';
import { useFocusEffect, useLocalSearchParams, router } from 'expo-router';
import { Button, Card, Input, Status } from '@/components/UI';
import { createPropertyComplianceItem, listPropertyCompliance } from '@/lib/api';
import { useTheme } from '@/lib/theme';

export default function PropertyCompliance(){
 const {id}=useLocalSearchParams<{id:string}>(); const {colors}=useTheme(); const [items,setItems]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [title,setTitle]=useState(''); const [type,setType]=useState('Safety certificate');
 const load=useCallback(async()=>{if(!id)return;try{setItems(await listPropertyCompliance(id))}catch(e){Alert.alert('Could not load compliance',e instanceof Error?e.message:'Please try again.')}finally{setLoading(false)}},[id]); useFocusEffect(useCallback(()=>{void load()},[load]));
 if(loading)return <View style={[s.center,{backgroundColor:colors.bg}]}><ActivityIndicator color={colors.primary}/></View>;
 return <ScrollView contentContainerStyle={[s.page,{backgroundColor:colors.bg}]}><Text style={[s.kicker,{color:colors.muted}]}>HOME PASSPORT · COMPLIANCE</Text><Text style={[s.title,{color:colors.text}]}>Property compliance</Text><Text style={[s.sub,{color:colors.muted}]}>Record applicable property certificates, inspections and expiry dates. MEND provides record keeping and reminders; it does not determine legal obligations.</Text><Card><Input label="Record title" value={title} onChangeText={setTitle} placeholder="Gas safety certificate"/><Input label="Type" value={type} onChangeText={setType} placeholder="Certificate type"/><Button title="Add compliance record" onPress={async()=>{if(!id||!title.trim())return;try{await createPropertyComplianceItem({propertyId:id,title:title.trim(),complianceType:type.trim()});setTitle('');await load()}catch(e){Alert.alert('Could not save',e instanceof Error?e.message:'Please try again.')}}}/></Card>{items.map(x=><Card key={x.id}><View style={s.row}><View style={{flex:1}}><Text style={[s.item,{color:colors.text}]}>{x.title}</Text><Text style={[s.meta,{color:colors.muted}]}>{x.compliance_type}</Text></View><Status text={x.status} type={x.status==='valid'?'success':x.status==='expired'?'danger':'warning'}/></View>{x.expires_at&&<Text style={[s.meta,{color:colors.muted}]}>Expires {new Date(x.expires_at).toLocaleDateString('en-GB')}</Text>}</Card>)}<Button title="Back to Home Passport" variant="ghost" onPress={()=>router.back()}/></ScrollView>
}
const s=StyleSheet.create({page:{padding:20,paddingTop:58,gap:14,flexGrow:1},center:{flex:1,alignItems:'center',justifyContent:'center'},kicker:{fontSize:11,fontWeight:'900',letterSpacing:1.5},title:{fontSize:30,fontWeight:'900'},sub:{fontSize:14,lineHeight:22},row:{flexDirection:'row',alignItems:'center',gap:12},item:{fontSize:16,fontWeight:'900',textTransform:'capitalize'},meta:{fontSize:12,marginTop:4}});