import { supabase } from './supabase';

function requireSupabase() {
  if (!supabase) throw new Error('Supabase is not configured. Add EXPO_PUBLIC_SUPABASE_URL and EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY.');
  return supabase;
}

export async function currentUser() { const client=requireSupabase(); const {data,error}=await client.auth.getUser(); if(error) throw error; return data.user; }
export async function listProperties(){const c=requireSupabase();const{data,error}=await c.from('properties').select('*').order('created_at',{ascending:true});if(error)throw error;return data??[];}
export async function listTenantProperties(){const c=requireSupabase();const u=await currentUser();if(!u)return[];const{data,error}=await c.from('property_members').select('property_id,member_role,can_view,can_create_repair,properties(*)').eq('user_id',u.id).eq('can_view',true);if(error)throw error;return data??[];}
export async function requestPropertyAccess(propertyId:string,note?:string){const c=requireSupabase();const u=await currentUser();if(!u)throw new Error('Please sign in.');const{data,error}=await c.from('property_access_requests').insert({property_id:propertyId,requester_id:u.id,requested_role:'tenant',note:note?.trim()||null}).select().single();if(error)throw error;return data;}
export async function listMyPropertyAccessRequests(){const c=requireSupabase();const u=await currentUser();if(!u)return[];const{data,error}=await c.from('property_access_requests').select('*,properties(*)').eq('requester_id',u.id).order('created_at',{ascending:false});if(error)throw error;return data??[];}
export async function listPropertyAccessRequests(propertyId:string){const c=requireSupabase();const{data,error}=await c.from('property_access_requests').select('*,profiles:requester_id(first_name,last_name,email)').eq('property_id',propertyId).order('created_at',{ascending:false});if(error)throw error;return data??[];}
export async function reviewPropertyAccessRequest(requestId:string,approve:boolean){const c=requireSupabase();const{data,error}=await c.rpc('approve_property_access_request',{p_request_id:requestId,p_approve:approve});if(error)throw error;return data;}
export async function getTenantRepairs(){const c=requireSupabase();const u=await currentUser();if(!u)return[];const{data,error}=await c.from('repairs').select('*,properties(*),trade_profiles(*)').or(`tenant_id.eq.${u.id},customer_id.eq.${u.id}`).order('created_at',{ascending:false});if(error)throw error;return data??[];}
export async function createProperty(input:{name:string;address_line1:string;city:string;postcode:string;property_type?:string}){const c=requireSupabase();const u=await currentUser();if(!u)throw new Error('Please sign in.');const{data,error}=await c.from('properties').insert({property_type:input.property_type??'House',ownership_type:'owner_occupier',address_line_1:input.address_line1,city:input.city,postcode:input.postcode,country:'England',owner_id:u.id}).select().single();if(error)throw error;return data;}
export async function createRepair(input:{property_id:string;category:string;title:string;description:string;urgency:string;media?:unknown[];triage_session_id?:string;safety_level?:string;safety_notes?:string;ai_summary?:string;ai_recommended_action?:string;ai_confidence?:number}){const c=requireSupabase();const u=await currentUser();if(!u)throw new Error('Please sign in.');const{data:membership}=await c.from('property_members').select('member_role,can_create_repair').eq('property_id',input.property_id).eq('user_id',u.id).maybeSingle();const tenantId=membership?.member_role==='tenant'&&membership?.can_create_repair?u.id:null;const{data,error}=await c.from('repairs').insert({customer_id:u.id,tenant_id:tenantId,property_id:input.property_id,category_id:(await c.from('service_categories').select('id').eq('name',input.category).maybeSingle()).data?.id??null,title:input.title,description:input.description,urgency:input.urgency,is_emergency:input.urgency==='emergency',status:'submitted',triage_session_id:input.triage_session_id??null,safety_level:input.safety_level??'standard',safety_notes:input.safety_notes??null,ai_summary:input.ai_summary??null,ai_recommended_action:input.ai_recommended_action??null,ai_confidence:input.ai_confidence??null}).select().single();if(error)throw error;return data;}
export async function listRepairs(){const c=requireSupabase();const u=await currentUser();if(!u)return[];const{data,error}=await c.from('repairs').select('*, properties(*), trade_profiles(*)').eq('customer_id',u.id).order('created_at',{ascending:false});if(error)throw error;return data??[];}
export async function getRepair(id:string){const c=requireSupabase();const{data,error}=await c.from('repairs').select('*, properties(*), trade_profiles(*)').eq('id',id).single();if(error)throw error;return data;}
export async function listTrades(category?:string){const c=requireSupabase();let query=c.from('trade_profiles').select('*, trade_services(*), trade_verifications(*)').eq('is_active',true);if(category){const{data:cats,error:catError}=await c.from('service_categories').select('id').ilike('name',`%${category}%`).limit(1);if(catError)throw catError;if(cats?.[0]){const{data:ts,error:tsError}=await c.from('trade_services').select('trade_id').eq('service_id',cats[0].id);if(tsError)throw tsError;const ids=(ts??[]).map((x:any)=>x.trade_id);if(!ids.length)return[];query=query.in('id',ids);}else return[];}const{data,error}=await query.order('average_rating',{ascending:false}).limit(50);if(error)throw error;return data??[];}
export async function requestQuote(repairId:string,tradeId:string,message:string){const c=requireSupabase();const u=await currentUser();if(!u)throw new Error('Please sign in.');const{data:repair,error:repairError}=await c.from('repairs').select('id, customer_id').eq('id',repairId).single();if(repairError)throw repairError;if(repair.customer_id!==u.id)throw new Error('You are not authorised for this repair.');const{data:trade,error:tradeError}=await c.from('trade_profiles').select('user_id').eq('id',tradeId).single();if(tradeError)throw tradeError;const{data:conversation,error}=await c.from('conversations').insert({repair_id:repairId,conversation_type:'repair'}).select().single();if(error)throw error;await c.from('conversation_members').insert([{conversation_id:conversation.id,user_id:u.id},{conversation_id:conversation.id,user_id:trade.user_id}]);await c.from('messages').insert({conversation_id:conversation.id,sender_id:u.id,body:message});return conversation;}
export async function invokeTriage(payload:{description:string;category?:string}){const c=requireSupabase();const{data,error}=await c.functions.invoke('mend-triage',{body:payload});if(error)throw error;return data;}
export async function acceptQuote(quoteId:string){const c=requireSupabase();const{data,error}=await c.functions.invoke('accept-quote',{body:{quoteId}});if(error)throw error;return data;}
export async function createAppointment(repairId:string,startTime:string,endTime:string,accessNotes?:string){return bookAppointment(repairId,startTime,endTime,accessNotes);}
export async function sendMessage(conversationId:string,body:string){const c=requireSupabase();const{data,error}=await c.functions.invoke('send-message',{body:{conversationId,body}});if(error)throw error;return data;}
export async function registerTrade(input:{businessName?:string;displayName:string;bio?:string;yearsExperience?:number;radiusMiles?:number}){const c=requireSupabase();const{data,error}=await c.functions.invoke('register-trade',{body:input});if(error)throw error;return data;}
export type Property={id:string;owner_id:string|null;property_type:string;ownership_type:string;address_line_1:string;address_line_2:string|null;city:string;postcode:string;country:string;latitude:number|null;longitude:number|null;created_at:string;updated_at:string};
export type PropertyRoom={id:string;property_id:string;name:string;room_type:string|null;floor:string|null;notes:string|null};
export type PropertyAsset={id:string;property_id:string;room_id:string|null;name:string;asset_type:string;brand:string|null;model:string|null;serial_number:string|null;installed_on:string|null;warranty_end:string|null;notes:string|null};
export async function getProperty(id:string){const c=requireSupabase();const{data,error}=await c.from('properties').select('*').eq('id',id).single();if(error)throw error;return data as Property;}
export async function getPropertyPassport(id:string){const c=requireSupabase();const[property,rooms,assets,repairs,maintenance,documents]=await Promise.all([c.from('properties').select('*').eq('id',id).single(),c.from('property_rooms').select('*').eq('property_id',id).order('name'),c.from('property_assets').select('*').eq('property_id',id).order('name'),c.from('repairs').select('*').eq('property_id',id).order('created_at',{ascending:false}),c.from('maintenance_records').select('*').eq('property_id',id).order('performed_on',{ascending:false}),c.from('property_documents').select('*').eq('property_id',id).order('created_at',{ascending:false})]);for(const r of [property,rooms,assets,repairs,maintenance,documents])if(r.error)throw r.error;return{property:property.data,rooms:rooms.data??[],assets:assets.data??[],repairs:repairs.data??[],maintenance:maintenance.data??[],documents:documents.data??[]};}
export async function bookAppointment(repairId:string,startTime:string,endTime:string,accessNotes?:string){const c=requireSupabase();const{data,error}=await c.functions.invoke('book-appointment',{body:{repairId,startTime,endTime,accessNotes}});if(error)throw error;return data;}
export async function transitionRepairStatus(repairId:string,status:string){const c=requireSupabase();const{data,error}=await c.functions.invoke('transition-repair-status',{body:{repairId,status}});if(error)throw error;return data;}
