import { Alert, FlatList, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { useCallback, useEffect, useState } from 'react';
import { listConversationMessages, markConversationRead, sendMessage } from '@/lib/api';
import { theme } from '@/constants/theme';
import { currentUser } from '@/lib/api';
import { supabase } from '@/lib/supabase';

export default function Conversation() {
  const { id } = useLocalSearchParams<{id:string}>(); const [items,setItems]=useState<any[]>([]); const [body,setBody]=useState(''); const [sending,setSending]=useState(false); const [uid,setUid]=useState<string|null>(null);
  const load=useCallback(async()=>{if(!id)return; try{const [messages,user]=await Promise.all([listConversationMessages(id),currentUser()]);setItems(messages);setUid(user?.id??null);await markConversationRead(id);}catch(e){Alert.alert('Unable to load conversation',e instanceof Error?e.message:'Please try again.')}},[id]);
  useEffect(()=>{void load(); if(!supabase||!id)return; const channel=supabase.channel('conversation:'+id).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:'conversation_id=eq.'+id},()=>void load()).subscribe(); return()=>{void supabase.removeChannel(channel)}},[load,id]);
  const send=async()=>{if(!id||!body.trim()||sending)return;setSending(true);try{await sendMessage(id,body.trim());setBody('');await load()}catch(e){Alert.alert('Message failed',e instanceof Error?e.message:'Please try again.')}finally{setSending(false)}};
  return <KeyboardAvoidingView style={s.page} behavior={Platform.OS==='ios'?'padding':undefined}><View style={s.header}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹ Back</Text></Pressable><Text style={s.h}>Conversation</Text></View><FlatList data={items} keyExtractor={m=>m.id} contentContainerStyle={{paddingVertical:16}} renderItem={({item})=><View style={[s.bubble,item.sender_id===uid?s.mine:s.theirs]}><Text style={{color:item.sender_id===uid?'#fff':theme.colors.text}}>{item.body}</Text><Text style={[s.stamp,{color:item.sender_id===uid?'#DDE8EC':theme.colors.muted}]}>{new Date(item.sent_at).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}{item.sender_id===uid && item.read_at ? ' · Read' : ''}</Text></View>}/><View style={s.composer}><TextInput value={body} onChangeText={setBody} multiline maxLength={4000} placeholder="Write a message" placeholderTextColor={theme.colors.muted} style={s.input}/><Pressable disabled={sending||!body.trim()} onPress={()=>void send()} style={[s.send,(sending||!body.trim())&&s.disabled]}><Text style={s.sendText}>{sending?'…':'Send'}</Text></Pressable></View></KeyboardAvoidingView>
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:theme.colors.bg,padding:16,paddingTop:56},header:{gap:10},back:{fontSize:16,fontWeight:'800',color:theme.colors.primary},h:{fontSize:28,fontWeight:'900',color:theme.colors.text},bubble:{maxWidth:'82%',padding:12,borderRadius:16,marginBottom:8},mine:{alignSelf:'flex-end',backgroundColor:theme.colors.primary},theirs:{alignSelf:'flex-start',backgroundColor:theme.colors.surface,borderWidth:1,borderColor:theme.colors.line},stamp:{fontSize:10,marginTop:5},composer:{flexDirection:'row',gap:8,alignItems:'flex-end',paddingBottom:10},input:{flex:1,minHeight:48,maxHeight:120,borderWidth:1,borderColor:theme.colors.line,borderRadius:14,padding:12,color:theme.colors.text,backgroundColor:theme.colors.surface},send:{paddingHorizontal:17,paddingVertical:14,borderRadius:14,backgroundColor:theme.colors.primary},disabled:{opacity:.45},sendText:{color:'#fff',fontWeight:'900'}});
