-- MEND UK Phase 7: Booking & Scheduling
alter table public.appointments enable row level security;
create index if not exists idx_appointments_trade_time on public.appointments(trade_id,start_time,end_time,status);
create index if not exists idx_appointments_repair_status on public.appointments(repair_id,status,created_at desc);
drop policy if exists "appointments involved" on public.appointments;
create policy "appointments involved read" on public.appointments for select to authenticated using (customer_id=(select auth.uid()) or exists(select 1 from public.trade_profiles tp where tp.id=trade_id and tp.user_id=(select auth.uid())) or public.is_admin());
create or replace function public.book_appointment(p_repair_id uuid,p_start timestamptz,p_end timestamptz,p_access_notes text default null) returns public.appointments language plpgsql security invoker set search_path=public as $$ declare r public.repairs; a public.appointments; tp public.trade_profiles; v_weekday int; v_start time; v_end time; begin if p_end <= p_start then raise exception 'End time must be after start time'; end if; if p_start < now() then raise exception 'Appointment must be in the future'; end if; select * into r from public.repairs where id=p_repair_id for update; if not found or r.customer_id <> (select auth.uid()) then raise exception 'Not authorised'; end if; if r.status not in ('accepted','scheduled') then raise exception 'Repair is not ready to book'; end if; if r.assigned_trade_id is null then raise exception 'No trade is assigned'; end if; select * into tp from public.trade_profiles where id=r.assigned_trade_id; if not found or not tp.is_active then raise exception 'Trade is not active'; end if; if exists(select 1 from public.appointments where repair_id=r.id and status in ('proposed','requested','confirmed','rescheduled') and start_time < p_end and end_time > p_start) then raise exception 'This repair already has an overlapping appointment'; end if; if exists(select 1 from public.appointments where trade_id=r.assigned_trade_id and status in ('proposed','requested','confirmed','rescheduled') and start_time < p_end and end_time > p_start) then raise exception 'Trade is unavailable at this time'; end if; v_weekday := extract(isodow from p_start at time zone 'Europe/London'); v_start := (p_start at time zone 'Europe/London')::time; v_end := (p_end at time zone 'Europe/London')::time; if not exists(select 1 from public.trade_availability ta where ta.trade_id=r.assigned_trade_id and ta.weekday=v_weekday and ta.is_active=true and ta.start_time <= v_start and ta.end_time >= v_end) then raise exception 'Trade is not available during this window'; end if; insert into public.appointments(repair_id,trade_id,customer_id,start_time,end_time,status,access_notes) values(r.id,r.assigned_trade_id,r.customer_id,p_start,p_end,'requested',p_access_notes) returning * into a; return a; end; $$;
revoke execute on function public.book_appointment(uuid,timestamptz,timestamptz,text) from anon;
grant execute on function public.book_appointment(uuid,timestamptz,timestamptz,text) to authenticated;
create or replace function public.respond_appointment(p_appointment_id uuid,p_accept boolean) returns public.appointments language plpgsql security invoker set search_path=public as $$ declare a public.appointments; r public.repairs; begin select * into a from public.appointments where id=p_appointment_id for update; if not found then raise exception 'Appointment not found'; end if; select * into r from public.repairs where id=a.repair_id for update; if exists(select 1 from public.trade_profiles tp where tp.id=a.trade_id and tp.user_id=(select auth.uid())) then if a.status <> 'requested' then raise exception 'Appointment is not awaiting trade response'; end if; elsif r.customer_id <> (select auth.uid()) then raise exception 'Not authorised'; else raise exception 'Customer cannot directly confirm a requested appointment'; end if; if p_accept then if exists(select 1 from public.appointments x where x.trade_id=a.trade_id and x.id<>a.id and x.status in ('confirmed','rescheduled') and x.start_time<a.end_time and x.end_time>a.start_time) then raise exception 'Trade has another confirmed appointment in this window'; end if; update public.appointments set status='confirmed',updated_at=now() where id=a.id returning * into a; update public.repairs set status='scheduled',scheduled_start=a.start_time,scheduled_end=a.end_time,updated_at=now() where id=r.id and r.status in ('accepted','scheduled'); else update public.appointments set status='declined',updated_at=now() where id=a.id returning * into a; end if; return a; end; $$;
revoke execute on function public.respond_appointment(uuid,boolean) from anon;
grant execute on function public.respond_appointment(uuid,boolean) to authenticated;
create or replace function public.cancel_appointment(p_appointment_id uuid,p_reason text default null) returns public.appointments language plpgsql security invoker set search_path=public as $$ declare a public.appointments; r public.repairs; begin select * into a from public.appointments where id=p_appointment_id for update; if not found then raise exception 'Appointment not found'; end if; select * into r from public.repairs where id=a.repair_id; if r.customer_id <> (select auth.uid()) and not exists(select 1 from public.trade_profiles tp where tp.id=a.trade_id and tp.user_id=(select auth.uid())) and not public.is_admin() then raise exception 'Not authorised'; end if; if a.status not in ('requested','confirmed','rescheduled') then raise exception 'Appointment cannot be cancelled'; end if; update public.appointments set status='cancelled',access_notes=case when p_reason is null then access_notes else coalesce(access_notes,'')||E'\nCancellation: '||p_reason end,updated_at=now() where id=a.id returning * into a; if r.status='scheduled' and not exists(select 1 from public.appointments x where x.repair_id=r.id and x.id<>a.id and x.status in ('confirmed','rescheduled') and x.end_time>now()) then update public.repairs set status='accepted',scheduled_start=null,scheduled_end=null,updated_at=now() where id=r.id; end if; return a; end; $$;
revoke execute on function public.cancel_appointment(uuid,text) from anon;
grant execute on function public.cancel_appointment(uuid,text) to authenticated;
